artenv/artproject/artstore/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^store$', views.store, name='store'),
    url(r'^artistGalleryView/(?P<slug>[\w-]+)/$', views.artistGalleryView, name='artistGalleryView'),
    url(r'^detailed/(?P<slug>[\w-]+)/$', views.DetailedView, name='DetailedView'),
]

artenv/artproject/artwork/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('artstore.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

artenv/artproject/artstore/models.py
from django.db import models


# Create your models here.

class Product(models.Model):
    product_title = models.CharField(max_length=50)
    product_description = models.TextField()
    slug = models.SlugField(unique=True)
    price = models.DecimalField(max_digits=50, decimal_places=2)
    available = models.BooleanField()
    category = models.ForeignKey('Categorie')
    artist = models.ForeignKey('Artist')

    def __str__(self):
        return self.product_title


class Artist(models.Model):
    artist_name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    biography = models.TextField()
    phone = models.IntegerField()
    image = models.ImageField(null=True, blank=True)
    email = models.EmailField()

    def __str__(self):
        return self.artist_name


class Categorie(models.Model):
    category_title = models.CharField(max_length=50)
    category_description = models.TextField()
    active = models.BooleanField()

    def __str__(self):
        return self.category_title


class Image(models.Model):
    product = models.ForeignKey(Product)
    image_title = models.CharField(max_length=50)
    product_image = models.ImageField(upload_to='products/images/')
    display = models.BooleanField(default=False)


class Display(models.Model):
    display_title = models.CharField(max_length=50)
    display_image = models.ImageField(upload_to='display/images/')
    display = models.BooleanField(default=False)

    def __str__(self):
        return self.display_title

artenv/artproject/artstore/views.py
from django.shortcuts import render
from .models import Display, Product, Artist, Image, Categorie


# Create your views here.
def store(request):
    display = Display.objects.all()
    products = Product.objects.all()

    artists = Artist.objects.all()
    images = Image.objects.all()
    categories = Categorie.objects.all()

    context = {
        "display": display,
        "products": products,
        "artists": artists,
        "categories": categories,
        "images": images
    }
    return render(request, 'store1.html', context)


def artistGalleryView(request, slug):
    artist_product = Artist.objects.filter(slug=slug)
    artist = Artist.objects.get(slug=slug)

    display = Display.objects.all()
    products = Product.objects.filter(artist=artist_product)

    context = {
        "artist_product": artist_product,
        "display": display,
        "products": products,
        "artist": artist,
    }
    return render(request, 'ArtistDetailView.html', context)


def DetailedView(request, slug):
    products = Product.objects.get(slug=slug)
    artist_details = Artist.objects.get(artist_name=products.artist)
    print(artist_details.email)
    context = {
        "artist_details":artist_details,
        "products": products
    }
    return render(request, 'DetailedView.html', context)

artenv/artproject/artstore/templates/ArtistDetailView.html
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Artworks | Biography</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" src="{% static 'css/thumbnail-gallery.css'%}">
    <style>
        h2.featurette-heading, h2, h4, h3, h5,h6, p{
            color: white;
        }
        body{
        background-color: #616161;
        }
    </style>

</head>
<body >
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'store' %}">Store Gallery</a></li>
        <li><a href="#">About Us</a></li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Oil Paints</a></li>
          <li><a href="#">Sculptures</a></li>
          <li><a href="#">Morden Art</a></li>
        </ul>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user" style="color: orange;"></span> Sign in</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-user" style="color: #32cd32;"></span> Sign up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-shopping-cart" style="color: red;"></span> Cart</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container gallery-container">

    <div class="row featurette">
        <div class="col-md-7 push-md-5">
          <h2 class="featurette-heading" style="color: white;"> {{artist.artist_name}} | Artist.</h2>
            <h3><strong>Biography</strong> </h3>
            <hr>
          <p class="lead">{{artist.biography}}</p>
            <hr>
            <h4 class="featurette-heading"> <strong>Contacts  | </strong><i class="fa fa-envelope" aria-hidden="true"></i> {{artist.email}} | <i class="fa fa-phone" aria-hidden="true"></i> + {{artist.phone}} | <i class="fa fa-facebook" aria-hidden="true"></i> | <i class="fa fa-pinterest-square" aria-hidden="true"></i> | <i class="fa fa-twitter" aria-hidden="true"></i></h4>

        </div>
        <div class="col-md-5 pull-md-7">
           <img src="{{ MEDIA_URL }}{{artist.image}}" alt="Park" style=" width: 100%; height:200px; " >
        </div>
      </div>

    <h3>My Gallery</h3>

    <div class="tz-gallery">

        <div class="row">
    {% for product in products %}
        {% for product_img in product.image_set.all %}
            <div class="col-sm-6 col-md-3">
                <div class="thumbnail">
                    <a class="lightbox" href="{{ MEDIA_URL }}{{product_img.product_image}}">
                        <img src="{{ MEDIA_URL }}{{product_img.product_image}}" alt="Park" style=" width: 100%; height:200px; " >
                    </a>
                    <div class="caption">
                        <h4 > <a href="">{{product.product_title}}</a></h4>
                        <p style="color: black;">Price   :   <i class="fa fa-usd" aria-hidden="true"></i>{{product.price}}</p>
                        <p style="color: black;"><i class="fa fa-envelope-o" aria-hidden="true"></i> {{artist.email}}</p>
                        <p style="color: black;"><i class="fa fa-mobile" aria-hidden="true"></i> {{artist.phone}}</p>

                    </div>
                </div>
            </div>
            {% endfor %}
            {% endfor %}

    </div>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>
    <footer class="container-fluid text-center">
  <p>Gallery Store Copyright</p>
  <form class="form-inline">Get deals:
    <input type="email" class="form-control" size="50" placeholder="Email Address">
    <button type="button" class="btn btn-danger">Sign Up</button>
  </form>
</footer>
</div>
</body>
</html>

artenv/artproject/artstore/templates/DetailedView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ArtWorks</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" src="{% static 'css/thumbnail-gallery.css'%}">
    <style>
        h2, h4, h3, h5,h6 p{
            color: white;
        }
        body{
        background-color: #616161;
        }
    </style>

</head>
<body>

    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'store' %}">Store Gallery</a></li>
        <li><a href="#">About Us</a></li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Oil Paints</a></li>
          <li><a href="#">Sculptures</a></li>
          <li><a href="#">Morden Art</a></li>
        </ul>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user" style="color: orange;"></span> Sign in</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-user" style="color: #32cd32;"></span> Sign up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-shopping-cart" style="color: red;"></span> Cart</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
<br>


        {% for product_img in products.image_set.all %}

      <div class="row featurette">
          <div class="col-md-5 "  >
          <img src="{{ MEDIA_URL }}{{ product_img.product_image }}" alt="Park" style=" width: 100%; height:50%;" >
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading"><strong>Title |</strong>  {{ products.product_title}} </h2>
            <hr>
            <h4 class="featurette-heading"> <strong>Artist |</strong><a href="{% url 'artistGalleryView' artist_details.slug %}"> {{products.artist}}</a>  </h4>
            <h4 class="featurette-heading"> <strong>Price  | </strong>{{ products.price}} </h4>
            <h4 class="featurette-heading"> <strong>Type  | </strong> {{ products.category}} </h4>
            <h4 class="featurette-heading"> <strong>Contact  |</strong> {{artist_details.email}} </h4>


            <hr>
            <h3 class="featurette-heading"> <strong>  Description</strong> </h3>
            <hr>
          <p class="lead">{{ products.product_description }}</p>
        </div>
      </div>
    </a>
            {% endfor %}

      <hr class="featurette-divider">
    <footer class="container-fluid text-center">
  <p>Gallery Store Copyright</p>
  <form class="form-inline">Get deals:
    <input type="email" class="form-control" size="50" placeholder="Email Address">
    <button type="button" class="btn btn-danger">Sign Up</button>
  </form>
</footer>
</div>
</body>
</html>

artenv/artproject/artstore/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

artenv/artproject/artstore/templates/navbar.html
{% for display in display %}
<div class="jumbotron" style=" weight: 100%; height: auto; background-image: url('{{MEDIA_URL}}{{display.display_image}}');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: center;
    background-size: cover;">
  <div class="container text-center">
    <h1>ArtWorks Store</h1>
    <p>Showcasing Art Talent</p>
  </div>
</div>
{% endfor %}

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Products</a></li>
        <li><a href="#">Deals</a></li>
        <li><a href="#">Stores</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Your Account</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
      </ul>
    </div>
  </div>
</nav>

artenv/artproject/artstore/templates/store1.html
{% include 'base.html' %}
{% block content %}

{% for display in display %}
<div class="jumbotron" style=" weight: 100%; height: auto; background-image: url('{{MEDIA_URL}}{{display.display_image}}');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: center;
    background-size: cover;">
  <div class="container text-center">
    <h1 style="color: white;">ArtWorks Store</h1>
    <p style="color: white;">Showcasing Art Talent</p>
  </div>
</div>
{% endfor %}

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'store' %}">Store Gallery</a></li>
        <li><a href="#">About Us</a></li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Oil Paints</a></li>
          <li><a href="#">Sculptures</a></li>
          <li><a href="#">Morden Art</a></li>
        </ul>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user" style="color: orange;"></span> Sign in</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-user" style="color: #32cd32;"></span> Sign up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-shopping-cart" style="color: red;"></span> Cart</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    {% for product in products %}
        {% for product_img in product.image_set.all %}


            <div class="col-sm-3">
              <div class="panel panel-primary">
                  <div class="panel-heading" ><a href="{% url 'DetailedView' product.slug %}" style="color: white;">{{product.product_title}}</a></div>

                <div class="panel-body"><a href="{% url 'DetailedView' product.slug %}"><img src="{{ MEDIA_URL }}{{product_img.product_image}}" class="img-responsive" style="width:100%; height: 300px;" alt="Image"> </a> </div>

                  <div class="panel-footer">Artist: {{product.artist}} |  $: {{ product.price }}</div>
              </div>
            </div>

      {% endfor %}
    {% endfor %}
</div><br>

<br>

<footer class="container-fluid text-center">
  <p>Gallery Store Copyright</p>
  <form class="form-inline">Get deals:
    <input type="email" class="form-control" size="50" placeholder="Email Address">
    <button type="button" class="btn btn-danger">Sign Up</button>
  </form>
</footer>
</div>
{% endblock %}

artenv/artproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Gallery Store</title>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style  src="{% static 'css/bootstrap.js'%}"></style>
  <script  src="{% static 'js/bootstrap.min.js'%}"></script>
  <script  src="{% static 'js/bootstrap.js'%}"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }

    /* Remove the jumbotron's default bottom margin */
     .jumbotron {
      margin-bottom: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body style="background-color: #484848">
{% block content %}


{% endblock%}
</body>
</html>